exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('trails').del()
    .then(function() {
      // Inserts seed entries
      return knex('trails').insert([{
          id: 1,
          name: "McKenzie River Trail (MRT)",
          summary: "Rivers, bridges, lush terrain, waterfalls, blue pools, and technical riding.",
          difficulty: "blueBlack",
          stars: 4.6,
          url: "https://www.mtbproject.com/trail/212960/mckenzie-river-trail-mrt",
          location: "McKenzie Bridge, Oregon",
          mtbproject_id: 212960,
          img_medium: "https://cdn-files.apstatic.com/mtb/6305831_smallMed_1412281921.jpg",
          length: 25.4,
          ascent: 488,
          descent: -2197,
          high: 3147,
          low: 1430,
          longitude: 122.0015,
          longitude: 44.3936,
        }, {
          id: 2,
          mtbproject_id: 7015406,
          name: "Johnson Pass Trail",
          summary: "A great through-trail through classic Kenai Peninsula singletrack.",
          difficulty: "blueBlack",
          stars: 4.6,
          location: "Girdwood, Alaska",
          url: "https:\/\/www.mtbproject.com\/trail\/7015406\/johnson-pass-trail",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7012288_medium_1470613458.jpg",
          length: 23.7,
          ascent: 2094,
          descent: -2247,
          high: 1517,
          low: 518,
          longitude: -149.2776,
          latitude: 60.7243,
        }, {
          id: 3,
          mtbproject_id: 7003054,
          name: "Ouachita National Recreation Trail - IMBA Epic",
          summary: "This rough, rugged and remote trail is currently the longest mountain bike trail in Arkansas.",
          difficulty: "black",
          stars: 3.8,
          location: "Mena, Arkansas",
          url: "https:\/\/www.mtbproject.com\/trail\/7003054\/ouachita-national-recreation-trail-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7008596_medium_1457886340.jpg",
          length: 108.4,
          ascent: 13381,
          descent: -14826,
          high: 2596,
          low: 617,
          longitude: -94.3197,
          latitude: 34.6723,
        }, {
          mtbproject_id: 4308319,
          name: "Syllamo Trails - Bald Scrappy Loop",
          summary: "Not a well-maintained loop, especially for being part of an Epic ride.",
          difficulty: "blue",
          stars: 3.7,
          location: "Mountain View, Arkansas",
          url: "https:\/\/www.mtbproject.com\/trail\/4308319\/syllamo-trails-bald-scrappy-loop",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7000627_medium_1419964864.jpg",
          length: 7.1,
          ascent: 927,
          descent: -916,
          high: 919,
          low: 338,
          longitude: -92.1189,
          latitude: 35.9627,
          id: 3
        }, {
          mtbproject_id: 7002912,
          name: "Upper Buffalo Headwaters - IMBA EPIC",
          type: "Featured Ride",
          summary: "Remote backcountry singletrack in the heart of the Ozarks.",
          difficulty: "blueBlack",
          stars: 4.2,
          location: "Jasper, Arkansas",
          url: "https:\/\/www.mtbproject.com\/trail\/7002912\/upper-buffalo-headwaters-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7002516_medium_1431785583.jpg",
          length: 20.2,
          ascent: 2194,
          descent: -2202,
          high: 2512,
          low: 1769,
          longitude: -93.4949,
          latitude: 35.8573,
          id: 4
        }, {
          mtbproject_id: 7002912,
          name: "Upper Buffalo Headwaters - IMBA EPIC",
          type: "Featured Ride",
          summary: "Remote backcountry singletrack in the heart of the Ozarks.",
          difficulty: "blueBlack",
          stars: 4.2,
          location: "Jasper, Arkansas",
          url: "https:\/\/www.mtbproject.com\/trail\/7002912\/upper-buffalo-headwaters-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7002516_medium_1431785583.jpg",
          length: 20.2,
          ascent: 2194,
          descent: -2202,
          high: 2512,
          low: 1769,
          longitude: -93.4949,
          latitude: 35.8573,
          id:5
        }, {
            mtbproject_id: 7000113,
            name: "Black Canyon Trail (BCT) - IMBA EPIC",
            type: "Featured Ride",
            summary: "An exciting, long-distance singletrack experience through the foothills of the Bradshaw Mountains.",
            difficulty: "blueBlack",
            stars: 4.3,
            location: "Spring Valley, Arizona",
            url: "https:\/\/www.mtbproject.com\/trail\/7000113\/black-canyon-trail-bct-imba-epic",
            imgMedium: "https:\/\/cdn-files.apstatic.com\/mtb\/7002145_medium_1429887666.jpg",
            length: 77.7,
            ascent: 4411,
            descent: -7172,
            high: 4365,
            low: 1604,
            longitude: -112.1439,
            latitude: 34.4587,
        }, {
            mtbproject_id: 7005660,
            name: "Armstrong to Strawberry - IMBA EPIC",
            type: "Featured Ride",
            summary: "A point-to-point ride on a symphony of singletrack will leave your face sore from grinning!",
            difficulty: "blueBlack",
            stars: 5,
            "location": "South Lake Tahoe, California",
            url: "https:\/\/www.mtbproject.com\/trail\/7005660\/armstrong-to-strawberry-imba-epic",
            imgMedium: "https:\/\/cdn-files.apstatic.com\/mtb\/7003908_medium_1437192781.jpg",
            length: 38.7,
            ascent: 4692,
            descent: -6637,
            high: 9429,
            low: 5711,
            longitude: -119.9405,
            latitude: 38.8564,
        },






      ])
    })
}
