exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex('trails').del()
    .then(function() {
      // Inserts seed entries
      return knex('trails').insert([{
          id: 1,
          name: "McKenzie River Trail (MRT)",
          summary: "Rivers, bridges, lush terrain, waterfalls, blue pools, and technical riding.",
          difficulty: "blueBlack",
          stars: 4.6,
          url: "https://www.mtbproject.com/trail/212960/mckenzie-river-trail-mrt",
          location: "McKenzie Bridge, Oregon",
          mtbproject_id: 212960,
          img_medium: "https://cdn-files.apstatic.com/mtb/6305831_smallMed_1412281921.jpg",
          length: 25.4,
          ascent: 488,
          descent: -2197,
          high: 3147,
          low: 1430,
          longitude: 122.0015,
          longitude: 44.3936,
        }, {
          id: 2,
          mtbproject_id: 7015406,
          name: "Johnson Pass Trail",
          summary: "A great through-trail through classic Kenai Peninsula singletrack.",
          difficulty: "blueBlack",
          stars: 4.6,
          location: "Girdwood, Alaska",
          url: "https:\/\/www.mtbproject.com\/trail\/7015406\/johnson-pass-trail",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7012288_medium_1470613458.jpg",
          length: 23.7,
          ascent: 2094,
          descent: -2247,
          high: 1517,
          low: 518,
          longitude: -149.2776,
          latitude: 60.7243,
        }, {
          id: 3,
          mtbproject_id: 7003054,
          name: "Ouachita National Recreation Trail",
          summary: "This rough, rugged and remote trail is currently the longest mountain bike trail in Arkansas.",
          difficulty: "black",
          stars: 3.8,
          location: "Mena, Arkansas",
          url: "https:\/\/www.mtbproject.com\/trail\/7003054\/ouachita-national-recreation-trail-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7008596_medium_1457886340.jpg",
          length: 108.4,
          ascent: 13381,
          descent: -14826,
          high: 2596,
          low: 617,
          longitude: -94.3197,
          latitude: 34.6723,
        }, {
          mtbproject_id: 4308319,
          name: "Syllamo Trails - Bald Scrappy Loop",
          summary: "Not a well-maintained loop, especially for being part of an Epic ride.",
          difficulty: "blue",
          stars: 3.7,
          location: "Mountain View, Arkansas",
          url: "https:\/\/www.mtbproject.com\/trail\/4308319\/syllamo-trails-bald-scrappy-loop",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7000627_medium_1419964864.jpg",
          length: 7.1,
          ascent: 927,
          descent: -916,
          high: 919,
          low: 338,
          longitude: -92.1189,
          latitude: 35.9627,
          id: 4,
        }, {
          mtbproject_id: 7002912,
          name: "Upper Buffalo Headwaters",
          summary: "Remote backcountry singletrack in the heart of the Ozarks.",
          difficulty: "blueBlack",
          stars: 4.2,
          location: "Jasper, Arkansas",
          url: "https:\/\/www.mtbproject.com\/trail\/7002912\/upper-buffalo-headwaters-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7002516_medium_1431785583.jpg",
          length: 20.2,
          ascent: 2194,
          descent: -2202,
          high: 2512,
          low: 1769,
          longitude: -93.4949,
          latitude: 35.8573,
          id: 5,
        }, {
          mtbproject_id: 7002912,
          name: "Upper Buffalo Headwaters",
          summary: "Remote backcountry singletrack in the heart of the Ozarks.",
          difficulty: "blueBlack",
          stars: 4.2,
          location: "Jasper, Arkansas",
          url: "https:\/\/www.mtbproject.com\/trail\/7002912\/upper-buffalo-headwaters-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7002516_medium_1431785583.jpg",
          length: 20.2,
          ascent: 2194,
          descent: -2202,
          high: 2512,
          low: 1769,
          longitude: -93.4949,
          latitude: 35.8573,
          id: 6,
        }, {
          mtbproject_id: 7000113,
          name: "Black Canyon Trail (BCT)",
          summary: "An exciting, long-distance singletrack experience through the foothills of the Bradshaw Mountains.",
          difficulty: "blueBlack",
          stars: 4.3,
          location: "Spring Valley, Arizona",
          url: "https:\/\/www.mtbproject.com\/trail\/7000113\/black-canyon-trail-bct-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7002145_medium_1429887666.jpg",
          length: 77.7,
          ascent: 4411,
          descent: -7172,
          high: 4365,
          low: 1604,
          longitude: -112.1439,
          latitude: 34.4587,
          id: 7,
        }, {
          mtbproject_id: 7005660,
          name: "Armstrong to Strawberry",
          summary: "A point-to-point ride on a symphony of singletrack will leave your face sore from grinning!",
          difficulty: "blueBlack",
          stars: 5,
          location: "South Lake Tahoe, California",
          url: "https:\/\/www.mtbproject.com\/trail\/7005660\/armstrong-to-strawberry-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7003908_medium_1437192781.jpg",
          length: 38.7,
          ascent: 4692,
          descent: -6637,
          high: 9429,
          low: 5711,
          longitude: -119.9405,
          latitude: 38.8564,
          id: 8,
        }, {
          mtbproject_id: 7008693,
          name: "Big Boulder from Packer Saddle",
          summary: "You still have about 2000ft of climbing on your way, but descending Big Boulder is pure bliss!",
          difficulty: "blueBlack",
          stars: 4.5,
          location: "Downieville, California",
          url: "https:\/\/www.mtbproject.com\/trail\/7008693\/big-boulder-from-packer-saddle",
          img_medium: "https:\/\/img.youtube.com\/vi\/mSt2TcgM7NM\/hqdefault.jpg",
          length: 21.8,
          ascent: 1644,
          descent: -5813,
          high: 7095,
          low: 2896,
          longitude: -120.6666,
          latitude: 39.6145,
          id: 9,
        }, {
          mtbproject_id: 76708,
          name: "Big South Fork",
          summary: "A great IMBA Epic ride on the 5 mountain bike trails of Big South Fork.",
          difficulty: "blue",
          stars: 4.4,
          location: "Oneida, Tennessee",
          url: "https:\/\/www.mtbproject.com\/trail\/76708\/big-south-fork-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/73202_medium_.jpg",
          length: 34.2,
          ascent: 2249,
          descent: -2256,
          high: 1651,
          low: 1275,
          longitude: -84.6984,
          latitude: 36.4879,
          id: 10,
        },
        {
          id: 11,
          mtbproject_id: 86977,
          name: "Rattling Creek",
          summary: "Flowy trails punctuated with rock gardens create classic East Coast riding.",
          difficulty: "black",
          stars: 4,
          location: "Lykens, Pennsylvania",
          url: "https:\/\/www.mtbproject.com\/trail\/86977\/rattling-creek-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/143027_medium_.jpg",
          length: 22.3,
          ascent: 1739,
          descent: -1738,
          high: 1691,
          low: 922,
          longitude: -76.6893,
          latitude: 40.5446,
        },
        {
          id: 12,
          mtbproject_id: 87559,
          name: "North Umpqua",
          summary: "Endless singletrack through old growth forests in the Pacific Northwest",
          difficulty: "blueBlack",
          stars: 4.6,
          location: "Crater Lake, Oregon",
          url: "https:\/\/www.mtbproject.com\/trail\/87559\/north-umpqua-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/89161_medium_.jpg",
          length: 71.8,
          ascent: 4143,
          descent: -7880,
          high: 4532,
          low: 795,
          longitude: -122.0574,
          latitude: 43.2991,
        },
        {
          id: 13,
          mtbproject_id: 91627,
          name: "Maah Daah Hey",
          summary: "93 miles of North Dakota singletrack through painted buttes and tall grass prairies",
          difficulty: "blue",
          stars: 3.9,
          location: "Medora, North Dakota",
          url: "https:\/\/www.mtbproject.com\/trail\/91627\/maah-daah-hey-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/93874_medium_.jpg",
          length: 96.7,
          ascent: 8170,
          descent: -8706,
          high: 2703,
          low: 1996,
          longitude: -103.6751,
          latitude: 46.9549,
        },
        {
          id: 14,
          mtbproject_id: 134766,
          name: "Rock Lake",
          summary: "A linkup of deep woods singletrack - one of the longest skinny-trail routes in the Upper Midwest.",
          difficulty: "blueBlack",
          stars: 4.6,
          location: "Namakagon, Wisconsin",
          url: "https:\/\/www.mtbproject.com\/trail\/134766\/rock-lake-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/136082_medium_.jpg",
          length: 27,
          ascent: 1524,
          descent: -1524,
          high: 1595,
          low: 1420,
          longitude: -91.1354,
          latitude: 46.1976,
        },
        {
          id: 15,
          mtbproject_id: 169815,
          name: "Southern Traverse",
          summary: "Big mountain singletrack on the east coast - 3,000 feet of climbing for courage and endurance.",
          difficulty: "blueBlack",
          stars: 4.1,
          location: "Verona, Virginia",
          url: "https:\/\/www.mtbproject.com\/trail\/169815\/southern-traverse-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/180071_medium_.jpg",
          length: 36.4,
          ascent: 3946,
          descent: -3970,
          high: 3487,
          low: 1650,
          longitude: -79.3959,
          latitude: 38.2218,
        },
        {
          id: 16,
          mtbproject_id: 479729,
          name: "Colorado Trail: The Entire MTB Route",
          summary: "A life-changing ride on the Colorado Trail from Denver to Durango.",
          difficulty: "dblack",
          stars: 4.9,
          location: "Roxborough Park, Colorado",
          url: "https:\/\/www.mtbproject.com\/trail\/479729\/colorado-trail-the-entire-mtb-route-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7008681_medium_1458332514.jpg",
          length: 547.4,
          ascent: 71883,
          descent: -70453,
          high: 13238,
          low: 5506,
          longitude: -105.097,
          latitude: 39.4898,
        },
        {
          id: 17,
          mtbproject_id: 513404,
          name: "Fresno-Sauceda Loop",
          summary: "A huge ride with plenty of challenges.  Great opportunity to make it into a multi-day ride.",
          difficulty: "black",
          stars: 4.8,
          location: "Lajitas, Texas",
          url: "https:\/\/www.mtbproject.com\/trail\/513404\/fresno-sauceda-loop-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7007369_medium_1451529449.jpg",
          length: 59,
          ascent: 3914,
          descent: -3916,
          high: 4490,
          low: 2394,
          longitude: -103.7567,
          latitude: 29.273,
        },
        {
          id: 18,
          mtbproject_id: 523830,
          name: "Bull and Jake Mountain",
          summary: "Get ready for some red clay singletrack in the North Georgia Mountains.",
          difficulty: "blueBlack",
          stars: 4.4,
          location: "Dahlonega, Georgia",
          url: "https:\/\/www.mtbproject.com\/trail\/523830\/bull-and-jake-mountain-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/531979_medium_.jpg",
          length: 25.2,
          ascent: 2859,
          descent: -2856,
          high: 2645,
          low: 1506,
          longitude: -84.1442,
          latitude: 34.5828,
        },
        {
          id: 19,
          mtbproject_id: 565265,
          name: "Ellicottville Loop",
          summary: "An updated version of the 2002 IMBA Ellicottville Epic ride.",
          difficulty: "blueBlack",
          stars: 4.4,
          location: "Little Valley, New York",
          url: "https:\/\/www.mtbproject.com\/trail\/565265\/ellicottville-loop-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7022323_medium_1507583956.jpg",
          length: 29.9,
          ascent: 3127,
          descent: -3134,
          high: 2385,
          low: 1641,
          longitude: -78.6567,
          latitude: 42.2502,
        },
        {
          id: 20,
          mtbproject_id: 770094,
          name: "Kerr Scott",
          summary: "Bring on the Berms! This Epic ride incorporates all of the Kerr Scott trail systems.",
          difficulty: "blue",
          stars: 4.5,
          location: "Cricket, North Carolina",
          url: "https:\/\/www.mtbproject.com\/trail\/770094\/kerr-scott-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/845917_medium_.jpg",
          length: 33,
          ascent: 1860,
          descent: -1774,
          high: 1234,
          low: 979,
          longitude: -81.2238,
          latitude: 36.1352,
        },
        {
          id: 21,
          mtbproject_id: 845269,
          name: "Buffalo Creek Big Loop",
          summary: "A nice tour of some of the best of Buffalo Creek - mostly smooth singletrack with some climbing.",
          difficulty: "blue",
          stars: 4.6,
          location: "Pine, Colorado",
          url: "https:\/\/www.mtbproject.com\/trail\/845269\/buffalo-creek-big-loop-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7013659_medium_1474417646.jpg",
          length: 24.2,
          ascent: 2590,
          descent: -2586,
          high: 8054,
          low: 6672,
          longitude: -105.2744,
          latitude: 39.3866,
        },
        {
          id: 22,
          mtbproject_id: 846258,
          name: "Bangtail Divide",
          summary: "Close-to-town access to an intermediate but lengthy ride featuring views of multiple mountain ranges",
          difficulty: "blueBlack",
          stars: 4.5,
          location: "Bozeman, Montana",
          url: "https:\/\/www.mtbproject.com\/trail\/846258\/bangtail-divide-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7015112_medium_1478820225.jpg",
          length: 25,
          ascent: 3611,
          descent: -3309,
          high: 7923,
          low: 5479,
          longitude: -110.8758,
          latitude: 45.761,
        },
        {
          id: 23,
          mtbproject_id: 960984,
          name: "Mohican Mountain Bike Trail",
          summary: "One of Ohio's epic rides!",
          difficulty: "blueBlack",
          stars: 4.5,
          location: "Loudonville, Ohio",
          url: "https:\/\/www.mtbproject.com\/trail\/960984\/mohican-mountain-bike-trail",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7001710_medium_1426816304.jpg",
          length: 23.1,
          ascent: 1655,
          descent: -1655,
          high: 1349,
          low: 933,
          longitude: -82.2588,
          latitude: 40.6068,
        },
        {
          id: 24,
          mtbproject_id: 1221910,
          name: "Tahoe Rim & Flume Trail via Tahoe Meadows",
          summary: "An awesome high altitude ride through towering pines with majestic views of the Tahoe area.",
          difficulty: "blue",
          stars: 4.7,
          location: "Incline Village, Nevada",
          url: "https:\/\/www.mtbproject.com\/trail\/1221910\/tahoe-rim-flume-trail-via-tahoe-meadows",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/5751204_medium_1405212558.jpg",
          length: 24.6,
          ascent: 1455,
          descent: -3861,
          high: 8826,
          low: 6321,
          longitude: -119.9082,
          latitude: 39.3078,
        },
        {
          id: 25,
          mtbproject_id: 3579474,
          name: "Mid Mountain Loop",
          summary: "A challenging tour of classic Wasatch singletrack.",
          difficulty: "blueBlack",
          stars: 4.3,
          location: "Park City, Utah",
          url: "https:\/\/www.mtbproject.com\/trail\/3579474\/mid-mountain-loop-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7012015_medium_1469729179.jpg",
          length: 22.9,
          ascent: 2307,
          descent: -2351,
          high: 8454,
          low: 6657,
          longitude: -111.5154,
          latitude: 40.6569,
        },
        {
          id: 26,
          mtbproject_id: 3607752,
          name: "Tsali Left and Right Loops",
          summary: "Classic NC singletrack.",
          difficulty: "blue",
          stars: 4.3,
          location: "Bryson City, North Carolina",
          url: "https:\/\/www.mtbproject.com\/trail\/3607752\/tsali-left-and-right-loops-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/4306754_medium_1381886200.jpg",
          length: 24.8,
          ascent: 1707,
          descent: -1725,
          high: 2029,
          low: 1714,
          longitude: -83.5843,
          latitude: 35.4065,
        },
        {
          id: 27,
          mtbproject_id: 3671983,
          name: "Monarch Crest",
          summary: "One of Colorado's top 5 epic rides - classic high-altitude riding in the Rockies!",
          difficulty: "blueBlack",
          stars: 4.7,
          location: "Whitepine, Colorado",
          url: "https:\/\/www.mtbproject.com\/trail\/3671983\/monarch-crest-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7013256_medium_1473286247.jpg",
          length: 36.2,
          ascent: 2035,
          descent: -5890,
          high: 11962,
          low: 7458,
          longitude: -106.3254,
          latitude: 38.4965,
        },
        {
          id: 28,
          mtbproject_id: 3682158,
          name: "Surveyor's Ridge",
          summary: "Iconic PNW riding; tough and rugged Surveyor's Ridge Trail  with scenic postcard views of Mt. Hood.",
          difficulty: "blueBlack",
          stars: 4.3,
          location: "Odell, Oregon",
          url: "https:\/\/www.mtbproject.com\/trail\/3682158\/surveyors-ridge-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/4690526_medium_1388121592.jpg",
          length: 20.4,
          ascent: 3133,
          descent: -3506,
          high: 4377,
          low: 1776,
          longitude: -121.5661,
          latitude: 45.4657,
        },
        {
          id: 29,
          mtbproject_id: 3684835,
          name: "Rothrock TrailMix",
          summary: "An awesome expedition of the best tech and flow that Rothrock trails have to offer.",
          difficulty: "black",
          stars: 4.1,
          location: "Boalsburg, Pennsylvania",
          url: "https:\/\/www.mtbproject.com\/trail\/3684835\/rothrock-trailmix-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/3702308_medium_1375309588.jpg",
          length: 36.3,
          ascent: 4220,
          descent: -4215,
          high: 2412,
          low: 1333,
          longitude: -77.7561,
          latitude: 40.7651,
        },
        {
          id: 30,
          mtbproject_id: 3734125,
          name: "Waldo Lake Loop",
          summary: "A tough, but scenic all-singletrack loop around the tranquil and pristine Waldo Lake.",
          difficulty: "blue",
          stars: 4.1,
          location: "Oakridge, Oregon",
          url: "https:\/\/www.mtbproject.com\/trail\/3734125\/waldo-lake-loop-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7020349_medium_1501074500.jpg",
          length: 20.3,
          ascent: 1081,
          descent: -1075,
          high: 5754,
          low: 5421,
          longitude: -122.0045,
          latitude: 43.761,
        },
        {
          id: 31,
          mtbproject_id: 3801032,
          name: "Curt Gowdy State Park",
          summary: "A big loop that hits the highlights of both the mountain and reservoir trails.",
          difficulty: "blueBlack",
          stars: 4.4,
          location: "Cheyenne, Wyoming",
          url: "https:\/\/www.mtbproject.com\/trail\/3801032\/curt-gowdy-state-park-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7005273_medium_1442207572.jpg",
          length: 25.2,
          ascent: 2844,
          descent: -2846,
          high: 7684,
          low: 6844,
          longitude: -105.2073,
          latitude: 41.1605,
        },
        {
          id: 32,
          mtbproject_id: 4073073,
          name: "South Boundary Trail #164",
          summary: "This classic little-bit-of-everything sub-alpine forest ridge ride is consistently ranked among the best in New Mexico.",
          difficulty: "blueBlack",
          stars: 4.7,
          location: "Angel Fire, New Mexico",
          url: "https:\/\/www.mtbproject.com\/trail\/4073073\/south-boundary-trail-164",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7029245_medium_1541774207.jpg",
          length: 21.4,
          ascent: 1608,
          descent: -4384,
          high: 10710,
          low: 7171,
          longitude: -105.3182,
          latitude: 36.306,
        },
        {
          id: 33,
          mtbproject_id: 4091943,
          name: "Hurricane Rim Loop",
          summary: "A popular loop that combines three fun trails with easy climbs, fast descending, and great vistas.",
          difficulty: "blueBlack",
          stars: 4.1,
          location: "LaVerkin, Utah",
          url: "https:\/\/www.mtbproject.com\/trail\/4091943\/hurricane-rim-loop-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7016944_medium_1488814896.jpg",
          length: 24.1,
          ascent: 1523,
          descent: -1526,
          high: 4316,
          low: 3455,
          longitude: -113.2179,
          latitude: 37.2003,
        },
        {
          id: 34,
          mtbproject_id: 4550979,
          name: "Ape Canyon to Plains of Abraham",
          summary: "An amazing journey back in time to the scene of the Mt. St. Helens eruption.",
          difficulty: "blueBlack",
          stars: 4.7,
          location: "Amboy, Washington",
          url: "https:\/\/www.mtbproject.com\/trail\/4550979\/ape-canyon-to-plains-of-abraham-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7022790_medium_1509569210.jpg",
          length: 16.8,
          ascent: 2423,
          descent: -2423,
          high: 4556,
          low: 2915,
          longitude: -122.0923,
          latitude: 46.1655,
        },
        {
          id: 35,
          mtbproject_id: 6045531,
          name: "Goodwater Loop of Lake Georgetown",
          summary: "An excellent skills building trail with many scenic views.",
          difficulty: "blueBlack",
          stars: 3.7,
          location: "Serenada, Texas",
          url: "https:\/\/www.mtbproject.com\/trail\/6045531\/goodwater-loop-of-lake-georgetown-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7007500_medium_1452217129.jpg",
          length: 26.3,
          ascent: 837,
          descent: -842,
          high: 911,
          low: 802,
          longitude: -97.7388,
          latitude: 30.67,
        },
        {
          id: 36,
          mtbproject_id: 7002026,
          name: "South Yuba Trail: Missouri Bar to South Yuba Camp",
          summary: "A scenic technical ride along the South Yuba river",
          difficulty: "black",
          stars: 5,
          location: "Nevada City, California",
          url: "https:\/\/www.mtbproject.com\/trail\/7002026\/south-yuba-trail-missouri-bar-to-south-yuba-camp",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7002235_medium_1430535726.jpg",
          length: 8.7,
          ascent: 1121,
          descent: -1245,
          high: 2545,
          low: 2142,
          longitude: -120.8855,
          latitude: 39.346,
        },
        {
          id: 37,
          mtbproject_id: 7005013,
          name: "High Country Pathway",
          summary: "Michigan's longest loop trail crossing through three counties and covering varied terrain.",
          difficulty: "blueBlack",
          stars: 3.3,
          location: "Atlanta, Michigan",
          url: "https:\/\/www.mtbproject.com\/trail\/7005013\/high-country-pathway-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7015183_medium_1479156255.jpg",
          length: 82,
          ascent: 4615,
          descent: -4614,
          high: 1221,
          low: 766,
          longitude: -84.3623,
          latitude: 45.1154,
        },
        {
          id: 38,
          mtbproject_id: 7015267,
          name: "Spruce Knob to Seneca Creek",
          summary: "From the highest point in WV to the water falls of Seneca Creek, this ride has it all.",
          difficulty: "black",
          stars: 3.5,
          location: "Franklin, West Virginia",
          url: "https:\/\/www.mtbproject.com\/trail\/7015267\/spruce-knob-to-seneca-creek-imba-epic",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/3563124_medium_1374665408.jpg",
          length: 17.6,
          ascent: 1944,
          descent: -1950,
          high: 4844,
          low: 3111,
          longitude: -79.5499,
          latitude: 38.7119,
        },
        {
          id: 39,
          mtbproject_id: 7028664,
          name: "Galena Grinder 2017 Full Course",
          summary: "Our 2017 edition of The Galena Grinder, one of the longest running MTB races in Idaho.",
          difficulty: "blueBlack",
          stars: 4,
          location: "Sun Valley, Idaho",
          url: "https:\/\/www.mtbproject.com\/trail\/7028664\/galena-grinder-2017-full-course",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7019724_medium_1499282554.jpg",
          length: 26.2,
          ascent: 3310,
          descent: -3307,
          high: 8362,
          low: 7286,
          longitude: -114.6554,
          latitude: 43.873,
        },
        {
          id: 40,
          mtbproject_id: 7030503,
          name: "Aspen Snowmass Mega Loop",
          summary: "Singletrack overload, technical classics, modern flow, never-ending views. A worthy and rewarding ride to remember!",
          difficulty: "black",
          stars: 5,
          location: "Aspen, Colorado",
          url: "https:\/\/www.mtbproject.com\/trail\/7030503\/aspen-snowmass-mega-loop",
          img_medium: "https:\/\/cdn-files.apstatic.com\/mtb\/7027884_medium_1534783824.jpg",
          length: 59.9,
          ascent: 8190,
          descent: -8199,
          high: 10073,
          low: 7625,
          longitude: -106.8086,
          latitude: 39.1915,
        }
      ])
    }).then(() => {
      return knex.raw(
        `SELECT setval('trails_id_seq', (SELECT MAX(id) FROM trails));`
      )
    })
}
